create table public.tbl_addresses
(
    id           bigint generated by default as identity
        primary key,
    created_at   date,
    updated_at   date,
    address_line varchar(255),
    city         varchar(255),
    state        varchar(255)
);

alter table public.tbl_addresses
    owner to avnadmin;

create table public.tbl_amenities
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    status     smallint     not null
        constraint tbl_amenities_status_check
            check ((status >= 0) AND (status <= 1)),
    image_url  smallint     not null
        constraint tbl_amenities_image_url_check
            check ((image_url >= 0) AND (image_url <= 1)),
    name       varchar(255) not null
);

alter table public.tbl_amenities
    owner to avnadmin;

create table public.tbl_bussiness_qr_code
(
    id              bigint generated by default as identity
        primary key,
    created_at      date,
    updated_at      date,
    bank_name       varchar(255) not null,
    bank_short_name varchar(255) not null,
    card_number     varchar(255) not null,
    card_password   varchar(255) not null,
    qr_code_url     varchar(255) not null,
    status          boolean      not null
);

alter table public.tbl_bussiness_qr_code
    owner to avnadmin;

create table public.tbl_confirm_email
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    code       varchar(255),
    email      varchar(255) not null,
    expired_at timestamp(6)
);

alter table public.tbl_confirm_email
    owner to avnadmin;

create table public.tbl_customer_booking_infos
(
    id               bigint generated by default as identity
        primary key,
    created_at       date,
    updated_at       date,
    email            varchar(255) not null,
    name             varchar(255) not null,
    phone_number     varchar(255) not null
        constraint ukr0adnfcg1mqu4lxxm392fw8nn
            unique,
    special_requires varchar(255)
);

alter table public.tbl_customer_booking_infos
    owner to avnadmin;

create table public.tbl_facilities
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    category   smallint     not null
        constraint tbl_facilities_category_check
            check ((category >= 0) AND (category <= 1)),
    name       varchar(255) not null
);

alter table public.tbl_facilities
    owner to avnadmin;

create table public.tbl_invalidate_tokens
(
    token_id varchar(255) not null
        primary key,
    expired  timestamp(6)
);

alter table public.tbl_invalidate_tokens
    owner to avnadmin;

create table public.tbl_notifications
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    body       varchar(255) not null,
    sent_at    timestamp(6) not null,
    title      varchar(255) not null
);

alter table public.tbl_notifications
    owner to avnadmin;

create table public.tbl_preferences
(
    id          bigint generated by default as identity
        primary key,
    created_at  date,
    updated_at  date,
    description varchar(255),
    name        varchar(255) not null
);

alter table public.tbl_preferences
    owner to avnadmin;

create table public.tbl_price_per_days
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    day        timestamp(6) not null
        constraint ukdw7pxlya8xoxqcbt5tgufv2b5
            unique
);

alter table public.tbl_price_per_days
    owner to avnadmin;

create table public.tbl_users
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    age        integer,
    avatar_url varchar(255),
    email      varchar(255) not null
        constraint ukj562wwmipqt96rkoqbo0jc34
            unique,
    google_id  varchar(255),
    is_online  boolean,
    name       varchar(255),
    phone      varchar(255),
    username   varchar(255)
        constraint ukc190nfu2w5xwvexf9dv08grsq
            unique
);

alter table public.tbl_users
    owner to avnadmin;

create table public.tbl_admins
(
    user_id    bigint not null
        primary key
        constraint fk1471ld0pnkjwqujxb5rf1yuc9
            references public.tbl_users,
    created_at date,
    updated_at date,
    level      varchar(255)
        constraint tbl_admins_level_check
            check ((level)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[])),
    role       varchar(255)
        constraint tbl_admins_role_check
            check ((role)::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'HOST'::character varying, 'CUSTOMER'::character varying])::text[])),
    status     varchar(255)
        constraint tbl_admins_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

alter table public.tbl_admins
    owner to avnadmin;

create table public.tbl_complaints
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    status     smallint     not null
        constraint tbl_complaints_status_check
            check ((status >= 0) AND (status <= 1)),
    token      varchar(255) not null,
    admin_id   bigint       not null
        constraint fkbdg8w4cepo9hqygl2ufbbr3hj
            references public.tbl_admins
);

alter table public.tbl_complaints
    owner to avnadmin;

create table public.tbl_customer
(
    user_id       bigint not null
        primary key
        constraint fkm4u9unscdr632nh3psvvxe23y
            references public.tbl_users,
    created_at    date,
    updated_at    date,
    date_of_birth varchar(255),
    last_booking  varchar(255),
    qr_code_url   varchar(255),
    role          varchar(255)
        constraint tbl_customer_role_check
            check ((role)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'HOST'::character varying, 'CUSTOMER'::character varying])::text[])),
    status        varchar(255)
        constraint tbl_customer_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

alter table public.tbl_customer
    owner to avnadmin;

create table public.tbl_customer_list_preferences
(
    customer_user_id    bigint not null
        constraint fk1oo0y01flqdk2dtkaka5vg899
            references public.tbl_customer,
    list_preferences_id bigint not null
        constraint fkbcqrk359oqcwtxsinv3tmtr75
            references public.tbl_preferences,
    primary key (customer_user_id, list_preferences_id)
);

alter table public.tbl_customer_list_preferences
    owner to avnadmin;

create table public.tbl_hosts
(
    user_id       bigint       not null
        primary key
        constraint fk8e7h9orajt7bk2159wxg2k1em
            references public.tbl_users,
    created_at    date,
    updated_at    date,
    business_name varchar(255),
    qr_code_url   varchar(255),
    role          varchar(255) not null
        constraint tbl_hosts_role_check
            check ((role)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'HOST'::character varying, 'CUSTOMER'::character varying])::text[])),
    status        varchar(255)
        constraint tbl_hosts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

alter table public.tbl_hosts
    owner to avnadmin;

create table public.tbl_homestays
(
    address_id       bigint not null
        primary key
        constraint fkhao1u4f9wk0mmmad9h94nb315
            references public.tbl_addresses,
    created_at       date,
    updated_at       date,
    advanced_payment integer,
    category         varchar(255),
    description      varchar(255),
    max_guest        integer,
    min_guest        integer,
    num_bathrooms    integer,
    num_bedrooms     integer,
    num_beds         integer,
    num_kitchen      integer,
    rating           real,
    status           smallint
        constraint tbl_homestays_status_check
            check ((status >= 0) AND (status <= 3)),
    title            varchar(255),
    warning_count    integer,
    host_id          bigint not null
        constraint fkrj8qh1gbr6pf8ktker64i8mr8
            references public.tbl_hosts
);

alter table public.tbl_homestays
    owner to avnadmin;

create table public.tbl_amenities_list_homestay
(
    amenities_id             bigint not null
        constraint fk5tjtsnygbmegfyilyc0jr3xa5
            references public.tbl_amenities,
    list_homestay_address_id bigint not null
        constraint fkgsn2ujbthj1592lf3fv7pmc3s
            references public.tbl_homestays,
    primary key (amenities_id, list_homestay_address_id)
);

alter table public.tbl_amenities_list_homestay
    owner to avnadmin;

create table public.tbl_bills
(
    id                       bigint generated by default as identity
        primary key,
    created_at               date,
    updated_at               date,
    actual_checkin_time      timestamp(6),
    check_in                 timestamp(6) not null,
    check_out                timestamp(6) not null,
    code                     varchar(255) not null,
    status                   smallint     not null
        constraint tbl_bills_status_check
            check ((status >= 0) AND (status <= 11)),
    customer_id              bigint
        constraint fk4x5qcwwxs8tfwbywohvo6j6vs
            references public.tbl_customer,
    customer_booking_info_id bigint
        constraint fkiwj9503ki1uxv4fb0nymfoo20
            references public.tbl_customer_booking_infos,
    homestay_id              bigint
        constraint fkvprevn1qlq5f32sl4muv6xv6
            references public.tbl_homestays
);

alter table public.tbl_bills
    owner to avnadmin;

create table public.tbl_facilities_list_homestay
(
    facilities_id            bigint not null
        constraint fk9v3yvboh1coy0q02ajy4ju9q5
            references public.tbl_facilities,
    list_homestay_address_id bigint not null
        constraint fkl6oq94cvhnrrjgtq13ehais1s
            references public.tbl_homestays,
    primary key (facilities_id, list_homestay_address_id)
);

alter table public.tbl_facilities_list_homestay
    owner to avnadmin;

create table public.tbl_homestay_daily_prices
(
    id               bigint generated by default as identity
        primary key,
    created_at       date,
    updated_at       date,
    is_booked        boolean,
    price            real,
    homestay_id      bigint not null
        constraint fkps935ichvjbujkd25o391hffy
            references public.tbl_homestays,
    price_per_day_id bigint not null
        constraint fk2n48fa8eaw65hg9yjk5mbeixv
            references public.tbl_price_per_days
);

alter table public.tbl_homestay_daily_prices
    owner to avnadmin;

create table public.tbl_homestay_image
(
    id          bigint generated by default as identity
        primary key,
    created_at  date,
    updated_at  date,
    image_url   varchar(255) not null,
    is_primary  boolean      not null,
    homestay_id bigint       not null
        constraint fkh2qo4xospp3wwbks160fus9ak
            references public.tbl_homestays
);

alter table public.tbl_homestay_image
    owner to avnadmin;

create table public.tbl_homestay_rules
(
    id          bigint generated by default as identity
        primary key,
    created_at  date,
    updated_at  date,
    description varchar(255) not null,
    rule_type   smallint     not null
        constraint tbl_homestay_rules_rule_type_check
            check ((rule_type >= 0) AND (rule_type <= 1)),
    home_id     bigint       not null
        constraint fk3run6bmr379ofqs1x64oj5fdt
            references public.tbl_homestays
);

alter table public.tbl_homestay_rules
    owner to avnadmin;

create table public.tbl_homestay_penaties
(
    id              bigint generated by default as identity
        primary key,
    created_at      date,
    updated_at      date,
    reason          varchar(255),
    suspension_util timestamp(6),
    type            varchar(255),
    admin_id        bigint not null
        constraint fkspmod98ws81q7muh04clm9c50
            references public.tbl_admins,
    homestay_id     bigint not null
        constraint fkl2wvy510twjhyaahy38ro1ft8
            references public.tbl_homestays
);

alter table public.tbl_homestay_penaties
    owner to avnadmin;

create table public.tbl_homestays_list_amenities
(
    homestay_address_id bigint not null
        constraint fkcw74hfna86w2mwrx5jxprpknt
            references public.tbl_homestays,
    list_amenities_id   bigint not null
        constraint fkgbamdfnbwv0fxqnd5x6232da3
            references public.tbl_amenities,
    primary key (homestay_address_id, list_amenities_id)
);

alter table public.tbl_homestays_list_amenities
    owner to avnadmin;

create table public.tbl_homestays_list_facilities
(
    homestay_address_id bigint not null
        constraint fk2nwhs7ltd99mep1hcq00jqjs
            references public.tbl_homestays,
    list_facilities_id  bigint not null
        constraint fk3wsjdd9jem8t9eqwjeuqm9t4x
            references public.tbl_facilities,
    primary key (homestay_address_id, list_facilities_id)
);

alter table public.tbl_homestays_list_facilities
    owner to avnadmin;

create table public.tbl_preferences_list_customer
(
    preference_id         bigint not null
        constraint fk1vihe9vrlilws0tsvkmloccmp
            references public.tbl_preferences,
    list_customer_user_id bigint not null
        constraint fk5fkjdsxvipxb78dsmymhexfso
            references public.tbl_customer,
    primary key (preference_id, list_customer_user_id)
);

alter table public.tbl_preferences_list_customer
    owner to avnadmin;

create table public.tbl_reviews
(
    id          bigint generated by default as identity
        primary key,
    created_at  date,
    updated_at  date,
    comment     varchar(255) not null,
    rating      integer      not null,
    customer_id bigint
        constraint fkeqr79xwsbeoh1ixpxoohdr4ke
            references public.tbl_customer,
    homestay_id bigint
        constraint fk5u0wu9bedirqlpk0cc28dp0cb
            references public.tbl_homestays
);

alter table public.tbl_reviews
    owner to avnadmin;

create table public.tbl_images
(
    id           bigint generated by default as identity
        primary key,
    created_at   date,
    updated_at   date,
    image_url    varchar(255),
    is_primary   boolean not null,
    complaint_id bigint  not null
        constraint fkb4heaas2fkh59s81h2u0ec6un
            references public.tbl_complaints,
    homestay_id  bigint  not null
        constraint fke743i9i28xuugvsv9qer6d3q3
            references public.tbl_homestays,
    review_id    bigint  not null
        constraint fkow4dfn3ty70in8yblrd9w2ss
            references public.tbl_reviews
);

alter table public.tbl_images
    owner to avnadmin;

create table public.tbl_tokens
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    status     smallint     not null
        constraint tbl_tokens_status_check
            check ((status >= 0) AND (status <= 1)),
    token      varchar(255) not null,
    user_id    bigint       not null
        constraint fkkfjplg7sgqia2lkkly7xviq2a
            references public.tbl_users
);

alter table public.tbl_tokens
    owner to avnadmin;

create table public.tbl_transactions
(
    id           bigint generated by default as identity
        primary key,
    created_at   date,
    updated_at   date,
    amount       numeric(12, 2) not null,
    completed_at timestamp(6),
    status       smallint
        constraint tbl_transactions_status_check
            check ((status >= 0) AND (status <= 3)),
    type         smallint
        constraint tbl_transactions_type_check
            check ((type >= 0) AND (type <= 2)),
    bill         bigint         not null
        constraint fkaycg59hah3xuxx2oimlkprys5
            references public.tbl_bills,
    from_user    bigint         not null
        constraint fk8naej4t93neh4fmt3m50mkj1k
            references public.tbl_users,
    to_user      bigint         not null
        constraint fkuj40cgei8r28fty3c2p5qll9
            references public.tbl_users
);

alter table public.tbl_transactions
    owner to avnadmin;

create table public.tbl_users_preferences
(
    user_id        bigint not null
        constraint fk9mb0l4p59l5thql6gxgu28ild
            references public.tbl_users,
    preferences_id bigint not null
        constraint fkhyr7dkeaj3m7yiigctanc5948
            references public.tbl_preferences,
    primary key (user_id, preferences_id)
);

alter table public.tbl_users_preferences
    owner to avnadmin;

