create table public.tbl_confirm_email
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    code       varchar(255),
    email      varchar(255) not null,
    expired_at timestamp(6)
);

alter table public.tbl_confirm_email
    owner to avnadmin;

create table public.tbl_preferences
(
    id          bigint generated by default as identity
        primary key,
    created_at  date,
    updated_at  date,
    description varchar(255) not null,
    name        varchar(255) not null
);

alter table public.tbl_preferences
    owner to avnadmin;

create table public.tbl_users
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    age        integer,
    avatar_url varchar(255),
    email      varchar(255) not null
        constraint ukj562wwmipqt96rkoqbo0jc34
            unique,
    google_id  varchar(255),
    is_online  boolean,
    name       varchar(255),
    phone      varchar(255),
    username   varchar(255)
        constraint ukc190nfu2w5xwvexf9dv08grsq
            unique
);

alter table public.tbl_users
    owner to avnadmin;

create table public.tbl_admins
(
    user_id    bigint not null
        primary key
        constraint fk1471ld0pnkjwqujxb5rf1yuc9
            references public.tbl_users,
    created_at date,
    updated_at date,
    level      varchar(255)
        constraint tbl_admins_level_check
            check ((level)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[])),
    role       varchar(255)
        constraint tbl_admins_role_check
            check ((role)::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'HOST'::character varying, 'CUSTOMER'::character varying])::text[])),
    status     varchar(255)
        constraint tbl_admins_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

alter table public.tbl_admins
    owner to avnadmin;

create table public.tbl_customer
(
    user_id       bigint not null
        primary key
        constraint fkm4u9unscdr632nh3psvvxe23y
            references public.tbl_users,
    created_at    date,
    updated_at    date,
    date_of_birth varchar(255),
    last_booking  varchar(255),
    qr_code_url   varchar(255),
    role          varchar(255)
        constraint tbl_customer_role_check
            check ((role)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'HOST'::character varying, 'CUSTOMER'::character varying])::text[])),
    status        varchar(255)
        constraint tbl_customer_status_check
            check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

alter table public.tbl_customer
    owner to avnadmin;

create table public.tbl_hosts
(
    user_id       bigint       not null
        primary key
        constraint fk8e7h9orajt7bk2159wxg2k1em
            references public.tbl_users,
    created_at    date,
    updated_at    date,
    business_name varchar(255),
    qr_code_url   varchar(255),
    role          varchar(255) not null
        constraint tbl_hosts_role_check
            check ((role)::text = ANY
        ((ARRAY ['ADMIN'::character varying, 'HOST'::character varying, 'CUSTOMER'::character varying])::text[])),
    status        varchar(255)
        constraint tbl_hosts_status_check
            check ((status)::text = ANY
                   ((ARRAY ['PENDING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))
);

alter table public.tbl_hosts
    owner to avnadmin;

create table public.tbl_preferences_users
(
    preferences_id bigint not null
        constraint fklj5vkg04t8nvpdg94gvuer6ss
            references public.tbl_preferences,
    users_id       bigint not null
        constraint fks35wefxi46y8o9jlw0wfhiiwn
            references public.tbl_users,
    primary key (preferences_id, users_id)
);

alter table public.tbl_preferences_users
    owner to avnadmin;

create table public.tbl_tokens
(
    id         bigint generated by default as identity
        primary key,
    created_at date,
    updated_at date,
    status     smallint     not null
        constraint tbl_tokens_status_check
            check ((status >= 0) AND (status <= 1)),
    token      varchar(255) not null,
    user_id    bigint       not null
        constraint fkkfjplg7sgqia2lkkly7xviq2a
            references public.tbl_users
);

alter table public.tbl_tokens
    owner to avnadmin;

create table public.tbl_users_preferences
(
    user_id        bigint not null
        constraint fk9mb0l4p59l5thql6gxgu28ild
            references public.tbl_users,
    preferences_id bigint not null
        constraint fkhyr7dkeaj3m7yiigctanc5948
            references public.tbl_preferences,
    primary key (user_id, preferences_id)
);

alter table public.tbl_users_preferences
    owner to avnadmin;

