CREATE TABLE "users" (
                         "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "username" varchar(50) UNIQUE NOT NULL,
                         "email" varchar(100) UNIQUE NOT NULL,
                         "password" varchar(255) NOT NULL,
                         "full_name" varchar(100),
                         "phone" varchar(20),
                         "role" varchar(20) NOT NULL DEFAULT 'customer',
                         "is_online" bool,
                         "avatar_url" varchar(255),
                         "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                         "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                         "google_id" varchar(255)
);

CREATE TABLE "refresh_token" (
                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "user_id" int,
                                 "token" "VARCHAR(500)" NOT NULL,
                                 "status" varchar(20) DEFAULT 'active'
);

CREATE TABLE "addresses" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "address_line" varchar(255) NOT NULL,
                             "city" varchar(100) NOT NULL,
                             "state" varchar(100),
                             "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                             "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "admins" (
                          "user_id" int PRIMARY KEY,
                          "level" varchar(20) NOT NULL DEFAULT 'normal',
                          "status" varchar(20) DEFAULT 'active'
);

CREATE TABLE "customers" (
                             "user_id" int PRIMARY KEY,
                             "date_of_birth" date,
                             "status" varchar(20) DEFAULT 'active',
                             "qr_code_url" varchar(255),
                             "last_booking" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "preferences" (
                               "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               "name" varchar(100) UNIQUE NOT NULL,
                               "description" text,
                               "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "customer_preferences" (
                                        "customer_id" int,
                                        "preference_id" int,
                                        "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "hosts" (
                         "user_id" int PRIMARY KEY,
                         "bussiness_name" varchar(250),
                         "qr_code_url" varchar(255),
                         "status" varchar(20) DEFAULT 'pending'
);

CREATE TABLE "homestay_penalties" (
                                      "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      "homestay_id" int,
                                      "type" varchar(50),
                                      "reason" text,
                                      "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                                      "suspension_until" datetime,
                                      "admin_id" int
);

CREATE TABLE "homestays" (
                             "id" bigint,
                             "host_id" int,
                             "address_id" int,
                             "title" varchar(255),
                             "description" text,
                             "category" varchar(50) NOT NULL DEFAULT 'homestay',
                             "rating" float DEFAULT 0,
                             "max_guest" int,
                             "min_guest" int,
                             "num_bedrooms" int,
                             "num_beds" int,
                             "num_bathrooms" int,
                             "num_kitchen" int,
                             "status" varchar(20),
                             "advanced_payment" int,
                             "warning_count" int DEFAULT 0,
                             "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                             "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "homestay_images" (
                                   "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   "homestay_id" bigint,
                                   "image_url" varchar(255) NOT NULL,
                                   "is_primary" boolean DEFAULT false,
                                   "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "price_per_days" (
                                  "id" bigint,
                                  "day" date
);

CREATE TABLE "homestay_daily_prices" (
                                         "price_id" bigint,
                                         "homestay_id" bigint,
                                         "price" float,
                                         "isBooked" bool
);

CREATE TABLE "amenities" (
                             "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             "name" varchar(100) UNIQUE NOT NULL,
                             "description" text,
                             "image_url" varchar
);

CREATE TABLE "homestay_amenities" (
                                      "homestay_id" bigint,
                                      "amenity_id" int,
                                      "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "reviews" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "homestay_id" bigint,
                           "customer_id" int,
                           "rating" int NOT NULL,
                           "comment" text,
                           "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "review_images" (
                                 "id" bigint,
                                 "review_id" bigint,
                                 "image_url" varchar
);

CREATE TABLE "customer_booking_infos" (
                                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          "name" varchar(155),
                                          "email" varchar(255),
                                          "phone_number" varchar(15),
                                          "special_requires" text
);

CREATE TABLE "bills" (
                         "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         "code" varchar(8) UNIQUE,
                         "homestay_id" bigint,
                         "customer_id" int,
                         "customerBookingInfo_id" int UNIQUE NOT NULL,
                         "check_in" datetime NOT NULL,
                         "check_out" datetime NOT NULL,
                         "status" varchar(20),
                         "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "checkin_checkouts" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "bill_id" bigint UNIQUE,
                                     "verify_checkin_code" varchar(15) NOT NULL,
                                     "checkin_status" varchar(20) NOT NULL DEFAULT 'pending',
                                     "checkin_time" datetime,
                                     "checkout_time" datetime,
                                     "checkout_status" varchar(20) NOT NULL DEFAULT 'pending',
                                     "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                                     "updated_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "complaints" (
                              "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "bill_id" bigint,
                              "description" text,
                              "is_refunded" bool,
                              "statusHostVerify" varchar(20) NOT NULL DEFAULT 'pending',
                              "statusAdminVerify" varchar(20) NOT NULL DEFAULT 'pending',
                              "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                              "resolved_at" datetime,
                              "admin_id" int
);

CREATE TABLE "complaint_images" (
                                    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    "complaint_id" bigint,
                                    "image_url" varchar(255) NOT NULL,
                                    "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "transactions" (
                                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                "bill_id" bigint,
                                "complaint_id" bigint,
                                "from_user_id" int,
                                "to_user_id" int,
                                "amount" decimal(12,2) NOT NULL,
                                "type" varchar(50) NOT NULL,
                                "status" varchar(20) NOT NULL DEFAULT 'pending',
                                "created_at" datetime DEFAULT (CURRENT_TIMESTAMP),
                                "completed_at" datetime
);

CREATE TABLE "notifications" (
                                 "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 "title" varchar(255),
                                 "body" text,
                                 "sent_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "facilities" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar(100) UNIQUE NOT NULL,
                              "category" varchar(50),
                              "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "homestay_facilities" (
                                       "homestay_id" bigint,
                                       "facility_id" int,
                                       "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "homestay_rules" (
                                  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  "homestay_id" bigint,
                                  "description" text NOT NULL,
                                  "rule_type" bool DEFAULT true,
                                  "created_at" datetime DEFAULT (CURRENT_TIMESTAMP)
);

CREATE TABLE "bussiness_QRCodes" (
                                     "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "qr_code_url" varchar(255),
                                     "card_number" varchar(50),
                                     "card_password" varchar(155),
                                     "status" bool,
                                     "bank_name" varchar(255),
                                     "bank_shortName" varchar(55)
);

COMMENT ON COLUMN "reviews"."rating" IS '1-5 stars';

ALTER TABLE "refresh_token" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "admins" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "customers" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "customer_preferences" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("user_id");

ALTER TABLE "customer_preferences" ADD FOREIGN KEY ("preference_id") REFERENCES "preferences" ("id");

ALTER TABLE "hosts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "homestay_penalties" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");

ALTER TABLE "homestay_penalties" ADD FOREIGN KEY ("admin_id") REFERENCES "admins" ("user_id");

ALTER TABLE "homestays" ADD FOREIGN KEY ("host_id") REFERENCES "hosts" ("user_id");

ALTER TABLE "homestays" ADD FOREIGN KEY ("address_id") REFERENCES "addresses" ("id");

ALTER TABLE "homestay_images" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");

ALTER TABLE "homestay_daily_prices" ADD FOREIGN KEY ("price_id") REFERENCES "price_per_days" ("id");

ALTER TABLE "homestay_daily_prices" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");

ALTER TABLE "homestay_amenities" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");

ALTER TABLE "homestay_amenities" ADD FOREIGN KEY ("amenity_id") REFERENCES "amenities" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("user_id");

ALTER TABLE "review_images" ADD FOREIGN KEY ("review_id") REFERENCES "reviews" ("id");

ALTER TABLE "bills" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");

ALTER TABLE "bills" ADD FOREIGN KEY ("customer_id") REFERENCES "customers" ("user_id");

ALTER TABLE "bills" ADD FOREIGN KEY ("customerBookingInfo_id") REFERENCES "customer_booking_infos" ("id");

ALTER TABLE "checkin_checkouts" ADD FOREIGN KEY ("bill_id") REFERENCES "bills" ("id");

ALTER TABLE "complaints" ADD FOREIGN KEY ("bill_id") REFERENCES "bills" ("id");

ALTER TABLE "complaints" ADD FOREIGN KEY ("admin_id") REFERENCES "admins" ("user_id");

ALTER TABLE "complaint_images" ADD FOREIGN KEY ("complaint_id") REFERENCES "complaints" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("bill_id") REFERENCES "bills" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("complaint_id") REFERENCES "complaints" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("from_user_id") REFERENCES "users" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("to_user_id") REFERENCES "users" ("id");

ALTER TABLE "homestay_facilities" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");

ALTER TABLE "homestay_facilities" ADD FOREIGN KEY ("facility_id") REFERENCES "facilities" ("id");

ALTER TABLE "homestay_rules" ADD FOREIGN KEY ("homestay_id") REFERENCES "homestays" ("id");
